/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__SOFTSERIAL

#include <SoftwareSerial.h>

// RemoteXY connection settings 
#define REMOTEXY_SERIAL_RX 2
#define REMOTEXY_SERIAL_TX 3
#define REMOTEXY_SERIAL_SPEED 9600


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 124 bytes V19 
  { 255,0,0,5,0,117,0,19,0,0,0,66,76,85,69,84,79,79,84,72,
  32,80,82,79,74,69,67,84,32,52,0,21,2,106,200,200,84,1,1,3,
  0,129,16,38,71,29,56,6,88,8,64,24,66,76,85,69,84,79,79,84,
  72,32,80,82,79,74,69,67,84,32,52,0,72,18,67,57,57,59,26,39,
  39,12,166,140,2,26,0,0,0,0,0,0,200,66,0,0,0,0,73,63,
  67,7,76,122,28,21,36,4,128,0,2,26,0,0,0,0,0,0,200,66,
  0,0,0,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // output variables
  int8_t circularBar_01; // from 0 to 100
  float linearbar_01; // from 0 to 100

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#define POT_PIN A0


void setup() 
{
  RemoteXY_Init ();  // initialization by macros   
}

void loop() 
{ 
  RemoteXY_Handler();   
  int potValue = analogRead(POT_PIN);  // 0–1023

  uint8_t mappedValue = map(potValue, 0, 1023, 0, 100);

  RemoteXY.circularBar_01 = mappedValue;
  RemoteXY.linearbar_01   = mappedValue;

  RemoteXY_delay(50);

}
